tasks:
  - init: |
      composer install
      mysql -e 'create database slim'
      mysql slim < scripts/schema.sql
    command: php -S 0.0.0.0:8080 -t public

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
